<?php

namespace App\Repository;

/**
 * soortactiviteitenRepositoryphp
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoortactiviteitRepository extends \Doctrine\ORM\EntityRepository
{

}
